---
title: "Representing Categorical Data - Favorite Classes"
format: html
---

```{r}
library(tidyverse)
library(googlesheets4)
library(janitor)
```

```{r}
url = "https://docs.google.com/spreadsheets/d/1JmVLUjtSwcuxApJXFFYu7sbre7s0pHjOfz2bmnwDMnQ/edit?usp=sharing"
df = read_sheet(url) |> 
  clean_names()
```

# 1. Make a barplot of `what_is_your_favorite_core_class`

```{r}
df |> 
  ggplot() +
  aes(x = what_is_your_favorite_core_class,
      color = what_is_your_favorite_core_class,
      fill = what_is_your_favorite_core_class
      ) +
  geom_bar() +
  scale_color_brewer(type = "qual", palette = 6) +
  scale_fill_brewer(type = "qual", palette = 6) + 
  labs(color = NULL, fill = NULL)
```

# 2. Make a barplot of `what_is_your_favorite_elective_class`

```{r}
df |> 
  ggplot() +
  aes(x = what_is_your_favorite_elective_class,
      color = what_is_your_favorite_elective_class,
      fill = what_is_your_favorite_elective_class
      ) +
  geom_bar()
```

# 3. Make a stacked barplot of `what_is_your_favorite_core_class` and `what_is_your_favorite_elective_class`

```{r}
df |> 
  ggplot() +
  aes(x = what_is_your_favorite_core_class,
      color = what_is_your_favorite_elective_class,
      fill = what_is_your_favorite_elective_class
      ) +
  geom_bar() 
```

# 4. Make a side by side barplot of `what_is_your_favorite_core_class` and `what_is_your_favorite_elective_class`

```{r}
df |> 
  ggplot() +
  aes(x = what_is_your_favorite_core_class,
      color = what_is_your_favorite_elective_class,
      fill = what_is_your_favorite_elective_class
      ) +
  geom_bar(position = "dodge")   +
  coord_flip()
```
